service: emojifinder

provider:
  name: aws  # provider
  region: eu-west-1  # aws region
  memorySize: 1024  # optional, in MB, default is 1024
  timeout: 30  # optional, in seconds, default is 6

functions:
  emojifinder:
    image: <repositoryUri>
    events:
      - http:
          path: endpoint
          method: post
